fetch('https://cosa1.netlify.app/.netlify/functions/proxy', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    url: 'https://api.github.com/repos/netlify/netlify-status',
    method: 'GET',
    headers: { 'Authorization': 'Bearer ...' } // optional
  }),
});